REVOKE CONNECT ON DATABASE transaction_test FROM PUBLIC;
REVOKE USAGE, CREATE ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS loan_transaction;
REVOKE CREATE ON SCHEMA loan_transaction FROM PUBLIC;

-- migration user
CREATE ROLE migration_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE transaction_test TO migration_user;
GRANT USAGE, CREATE ON SCHEMA loan_transaction TO migration_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA loan_transaction GRANT ALL PRIVILEGES ON TABLES TO migration_user;

-- web user
CREATE ROLE web_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE transaction_test TO web_user;
GRANT USAGE ON SCHEMA loan_transaction TO web_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA loan_transaction TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA loan_transaction GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA loan_transaction GRANT SELECT, USAGE ON SEQUENCES TO web_user;
